### ISSUE TITLE
ESP32 selection

### ISSUE THREAD

**Issue by saltyautomation** [FutureProofHomes/Satellite1-Hardware#4]
Just curious it looks like you are planning on using an ESP32 S3. Is there a reason that you did not choose a newer chip that supports thread/matter and newer wifi protocols? Something like the C5 which also has psram support for running music assistant/lms?

**Comment by saltyautomation** [comment]
I realize now there are a few things that the ESP32 C5 does not have that would prevent it from being used. Hopefully Espressif Systems will have a newer S3 design that will meet the requirements and add newer wifi and lower power along with thread support.

**Comment by that1guy** [comment]
Correct.  No other Espressif chips meet all the requirements for Sa1 the build.  We hope newer more powerful chips will come out in the future, but for today it's ESP32-S3
